### ISSUE TITLE
Fix compiler warnings

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#151]
It would be nice to fix all compiler warnings and don't merge new PRs until they build without any warning. 
Compiler warnings sometimes reveal real bugs in code, but currently interesting warnings are deeply buried in less important ones, so they are easy to miss.

Example bug found by GCC:
https://github.com/oscarlab/graphene/blob/043346180281d53ae5659fa9399cdca7d3c773f7/LibOS/shim/src/ipc/shim_ipc_nsimpl.h#L379 (this commit is the current master at the time of writing).

**Comment by chiache** [comment]
Point taken. I believe this specific warning is fixed on the current master branch, but it will be great to fix other warnings.

One idea is to enable -Werror for gcc.

**Comment by mkow** [comment]
Nah, the bug is still there ;) Link: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/ipc/shim_ipc_nsimpl.h#L379

> One idea is to enable -Werror for gcc.
Maybe it's a better idea to enforce this only for Jenkins builds, so it won't be burdensome for developers when experimenting with code?

**Comment by chiache** [comment]
What's the warning? I don't think I see it on the master branch.

**Comment by chiache** [comment]
Maybe a different GCC version?

**Comment by mkow** [comment]
```
ipc/shim_ipc_nsimpl.h:379:54: warning: comparison of constant ‘0’ with boolean expression is always false [-Wbool-compare]
         if ((err == __add_range(r, off, 0, NULL, 0)) < 0) {
                                                      ^
```
My GCC is quite new (7.2.0, Ubuntu 17.10), that may explain why you don't see this warning.

**Comment by chiache** [comment]
I see. Indeed.

**Comment by donporter** [comment]
BTW, I totally agree with this direction.  I started at one point with -Werror and a few integer issues turned on, but timed out before I could finish.

**Comment by mkow** [comment]
We finally managed to resolve this issue, closing :tada:
