### ISSUE TITLE
BUG() called during execution of unlink05 test from LTP

### ISSUE THREAD

**Issue by anjalirai-intel** [oscarlab/graphene#2545]
## Description of the problem
unlink05 throwed Illegal instruction error at the 2nd test

## Steps to reproduce
Execute attached files
unlink05_setup in linux environment and unlink05_run with graphene-direct
$ ./unlink05_setup
$ graphene-direct ./unlink05_run

## Expected results
```
/root/Graphene_Master/LibOS/shim/test/ltp/ltp_src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 05m 00s
TPASS: unlink(/tmp/unlink05_file) succeeded
TPASS: unlink(/tmp/unlink05_fifo) succeeded

Summary:
passed   2
failed   0
skipped  0
warnings 0
```

## Actual results
```
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
TINFO: Timeout per run is 0h 05m 00s
TPASS: unlink(/tmp/unlink05_file) succeeded
[P17908:T2:unlink05_run] error: unknown PAL handle type: 1
[P17908:T2:unlink05_run] error: BUG() ../LibOS/shim/src/fs/chroot/fs.c:259
[P17908:T2:unlink05_run] error: Illegal instruction during Graphene internal execution at 0x7f99dfc2c29c (IP = +0x1a29c, VMID = 17908, TID = 2)
[P17905:shim] error: Child process (vmid: 0x45f4) got disconnected
/root/Graphene_Master/LibOS/shim/test/ltp/ltp_src/lib/tst_test.c:1300: TBROK: Test killed by SIGPWR!

Summary:
passed   1
failed   0
skipped  0
warnings 0
```

[unlink05.zip](https://github.com/oscarlab/graphene/files/6814933/unlink05.zip)

**Comment by pwmarcz** [comment]
Seems fixed by #2592.

**Comment by dimakuv** [comment]
@anjalirx-intel Could you verify on your side that the latest Graphene master has this fixed?

**Comment by anjalirai-intel** [comment]
Hi @dimakuv 

It is not throwing BUG error but the test is still failing

error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
TINFO: Timeout per run is 0h 05m 00s
TPASS: unlink(/tmp/unlink05_file) succeeded
TFAIL: unlink(/tmp/unlink05_fifo) failed: EACCES (13)

Summary:
passed   0
failed   0
skipped  0
warnings 0

**Comment by mkow** [comment]
@anjalirai-intel Please use markdown in your comments...
@pwmarcz Could you take a look at this?

**Comment by anjalirai-intel** [comment]
@mkow Comment Updated

**Comment by pwmarcz** [comment]
To recap, the scenario is: first create a FIFO on host, then try to delete it from inside Graphene. This will fail, because Graphene does not support host-level FIFOs, and fails with -EACCES on any attempt to access them (see #2592).

I don't think there's a good reason to support deleting such unrecognized files: it's not possible to create such files from inside Graphene anyway (`mknod` will create an _emulated_ FIFO), and we already log a warning about this.

**Comment by mkow** [comment]
Ok, then it seems that we can close this issue.

**Comment by dimakuv** [comment]
I agree with Pawel's assessment. Previously we had a bug in Graphene that kinda "allowed" the `unlink05` test but resulted in illegal-instruction segfault. Now we explicitly forbid scenarios like `unlink05` by cleanly returning `-EACCES`.

So this particular test `unlink05` can be considered "impossible" in Graphene and should always fail. That is, until the moment we have an important real-world application that would legitimately need to communicate with the FIFO pipe of the host.
