### ISSUE TITLE
memcached multi-threading issue

### ISSUE THREAD

**Issue by shmeni** [oscarlab/graphene#40]
Hey,

First, thanks for all the previous help. I'm trying to run the memcached benchmark yet the applications hangs unexpectedly in my experiments.

The configuration is:
Memcached: running the newly added example in the app dir with the cmdline (disabling UDP and working only with TCP for simplicity)
./memcached.manifest.sgx -u root -t 4 -m 500 -U 0 -p 11211

Memslap, with the cmdline:
./memslap --debug --concurrency=24 --servers=localhost --initial-load=100 --execute-number=10000
(memslap was compiled with VALUE_BYTES 4000 (in memslap.cc)

I'm getting the following outputs:
1. The application either hangs (showing to be stuck either after printing epoll_wait/futex_wait/futex_wake in the inline debugger).
2. assert failed bookkeep/shim_vma.c:128 !prev || prev->addr + prev->length <= tmp->addr (value:0)
3. Application pass (very rarely).

This is a small test that should show the bug which is more frequent on my larger test. The bigger experiment I'm attempting to run is with a working set of ~400MB. I.e., having --initial-load=80000 and executing either get or set commands against it with arbitrary number of threads in the client and the server.

Lastly, I've also tried running different configuration with memslap, memaslap and YCSB. All attempts behaves similarly.

**Comment by donporter** [comment]
Hi, 

Can you try the latest master?  We pushed some fixes for mmap, and some fixes (and some warnings) related to futex.  I am not confident this will necessarily fix your problem, but it probably won't hurt, and would be helpful to know if any of these symptoms improve.

**Comment by shmeni** [comment]
Thanks for the help!

I've tried to pull the fix, though for some reason graphene fails to compile for me now:

Traceback (most recent call last):
  File "/home/user/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 720, in <module>
    for key, val in get_trusted_files(manifest, args).items():
  File "/home/user/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 232, in get_trusted_files
    targets[key] = (val, resolve_uri(val))
  File "/home/user/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 203, in resolve_uri
    raise Exception('Cannot resolve ' + orig_uri + ' or the file does not exist.')
Exception: Cannot resolve file:../../../../Runtime/ld-linux-x86-64.so.2 or the file does not exist.
make[5]: *** [exec_victim.manifest.sgx] Error 1
make[4]: *** [pie.manifest.sgx] Error 2

**Comment by donporter** [comment]
Indeed. As a temporary work-around, you should be able to:

make SGX=1 install
make SGX=1 (again)

to get past this.

**Comment by donporter** [comment]
Just pushed some fixes to rework the build process.  Try again, but would probably be wise to 'make clean' first.  Sorry about this issue.

**Comment by shmeni** [comment]
Thanks for the help, pull clean and rebuild helped!

I'm afraid I'm now getting new errors in a loop-fashion, trying to run memcached with the above configuration:

Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 6)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 3)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 6)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 3)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 6)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 3)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 6)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 3)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 6)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 3)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 6)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 3)
Internal memory fault at 0x0 (IP = +0x87ffe, VMID = 889661223, TID = 6)

**Comment by donporter** [comment]
Do you have any insight into what the faulting address is doing?

**Comment by shmeni** [comment]
I'm really not sure, but I think it might got to do with a race due to futexes.
Specifically, I've tried to make shim_futex oblivious to timeout, i.e. under LibOS/shim/src/sys/shim_futex.c

I commented the following code:
`
            if (utime) {
                struct timespec *ts = (struct timespec*) utime;
                // Round to microsecs
                timeout_us = (ts->tv_sec * 1000000) + (ts->tv_nsec / 1000);
                // Check for the CLOCK_REALTIME flag
                if (futex_op == FUTEX_WAIT_BITSET)  {
                    // DEP 1/28/17: Should really differentiate clocks, but
                    // Graphene only has one for now.
                    //&& 0 != (op & FUTEX_CLOCK_REALTIME)) {
                    uint64_t current_time = DkSystemTimeQuery();
                    if (current_time == 0) {
                        ret = -EINVAL;
                        break;
                    }
                    timeout_us -= current_time;
                }
            }
`
Which resulted in the application running, though having the same issues as before, with memcached hanging after blasting it with multiple clients.

I tried to further test futexes and got to a hacky workaround that helped my tests to pass. 
Basically I noticed that for certain cases the internal lock() method used in futex sometimes gets entered by multiple threads. I'm definitely not sure  why that happens, but reading the inline debugger log with memcached running in graphene (assuming the prints in the log are ordered correctly) I saw the following:
1.  Two threads adding entries to the futex list but the list end size was 1 (so 1 thread was essentially unable to get wake notifications). 
Using a simple spin_lock around this futex list solved (1), 
2. Then some WAKE and WAIT calls got unordered reaching the do_futex method. So a WAKE to an empty list failed to wake a not yet WAITing thread. 
My hacky workaround is a simple retry for WAKEs in the case of an empty list after a specific threshold passes. This is far from optimal as I get this penalty all the time :(

Hope I'm not misleading you, and would really appreciate your help. Thanks!

**Comment by donporter** [comment]
Can I ask you to try the latest version of the code?  I fixed one bug related to lost wakes that may help your problem (haven't tried memcached yet).

**Comment by shmeni** [comment]
Thanks so much! This fix worked for my problem, the tests are now running to completion as far as I can tell. 

Two issues remain which might be of interest to you, however, they do not stop me from running the tests, and I'm not sure they are related to this issue:
1. The futex timeout still causes the Internal memory fault errors, removing it the tests run to completion.
2. Very rarely the tests will continue to crash with an error similar to: assert failed bookkeep/shim_vma.c:128 !prev || prev->addr + prev->length <= tmp->addr (value:0)
