### ISSUE TITLE
Graphene/LibOS/shim/test/native/proc.c  failed to work

### ISSUE THREAD

**Issue by zhangckid** [oscarlab/graphene#461]
I tested the Graphene/LibOS/shim/test/native/proc.c like that:

./pal_loader proc.manifest   
opendir /proc/1: Is a directory

and I use this codes re-check the graphene /proc status:
c-read-dir.c
#include <dirent.h>
#include <stdio.h>

int main(void) {
  DIR *d;
  struct dirent *dir;
  d = opendir("/proc");
  if (d) {
    while ((dir = readdir(d)) != NULL) {
      printf("%s\n", dir->d_name);
    }
    closedir(d);
  }
  return(0);
}

./pal_loader c-read-dir.manifest

But got nothing. 
The wiki said graphene support  /proc/[pid] to get process metadata , but I can't read anything except /proc/cpuinfo and /proc/meminfo in graphene.

related issue:
https://github.com/oscarlab/graphene/issues/36

**Comment by zhangckid** [comment]
Hi @chiache @donporter .
Any comments for this issue?
I have tried to release v0.6, but still have this issue.
By the way, if fixed this bug, can we read like this : /proc/self/exe ?
I see in old version can read /proc/self in #36.

Thanks

**Comment by donporter** [comment]
#408 was one related fix.  There may be others missing where the type may be wrong.

This does sound like a bug.

**Comment by zhangckid** [comment]
I have tried the #408, but not help for this issue.
I still can not see the /proc/self in graphene, as the same time, /proc/meminfo and /proc/cpuinfo working normally.

**Comment by donporter** [comment]
I can reproduce the issue.  I made a bit of progress on branch don/proc, but I haven't fixed the bug.

The current issue is that we don't have an open method for /proc/1.

**Comment by zhangckid** [comment]
Why we don't have an open method for /proc/1 ? 
I noticed that in old version graphene as #36 said, this test case worked normally.

**Comment by donporter** [comment]
I think this worked by accident on the old directory cache design.

Why we don't have an open, I'm not sure.  That is on my docket to look into.

**Comment by donporter** [comment]
I pushed some changes to this branch that will address your problem, but there are a few loose ends to deal with before it goes to master.

**Comment by zhangckid** [comment]
Hi Don,
I have tired your temp patch, the native proc test works.
But it still have some issues here, we can't read the /proc/self/exe.
I try to use a demo to read it, and found that graphene will do shim_write caused crash, like that:
[     1] ---- shim_open("/proc/self/exe",O_RDONLY|2000000,23254220220) ...
[     1] ---- return from shim_open(...) = -22
[     1] ---- shim_write(2,0x512d9c79823b,14) ...
/proc/self/exe[     1] ---- return from shim_write(...) = 14
[     1] ---- shim_write(2,0x512d9c61b442,7) ...
 errno [     1] ---- return from shim_write(...) = 7
[     1] ---- shim_write(2,0x512d9ab11a72,2) ...
22[     1] ---- return from shim_write(...) = 2
[     1] ---- shim_write(2,0x512d9c61b44b,1) ...

[     1] ---- return from shim_write(...) = 1
[     1] ---- shim_write(2,0x512d9c7461fd,13) ...
fatal error: [     1] ---- return from shim_write(...) = 13
[     1] ---- shim_write(2,0x512d9c79823b,14) ...
/proc/self/exe[     1] ---- return from shim_write(...) = 14
[     1] ---- shim_write(2,0x512d9c745e9c,1) ...

Any idea about this?

Thanks

**Comment by donporter** [comment]
It looks like the open is failing before the write.

**Comment by zhangckid** [comment]
Yes, you are right. It is failing in open.
I found in find_thread_link() we can't got the exec->dentry in 'exe' handle path.
I don't know why.

**Comment by zhangckid** [comment]
Hi don,
I think I found the root cause of the issue, graphene not support the readlink syscall.
The /proc/self/exe is a symbolic link, so it still can't return correct value.
And the LTP test case can't pass the readlink test too.
So it looks like we need enable this syscall first.
What do you think about this issue?

**Comment by donporter** [comment]
Thanks!  Better symlink support would be a nice feature. I would love to see a patch.  I'm not sure the developers will take this up immediately---at the moment our coding time is going toward stability of existing features.

**Comment by mkow** [comment]
This file was moved to `regression` directory and later renamed to `proc_common.c`. Now it runs as part of CI tests, so I guess this issue can be resolved. Some bugs mentioned in this thread are most likely still present, but they should be covered by #948.
